#!/bin/sh


lock(){
	i3-msg workspace 8
	i3-msg fullscreen disable
	alacritty -o window.startup_mode=Fullscreen -e bash -c 'sleep 0.1 && cmatrix -ab -C cyan' &
	pid1=$!
	sleep 0.2
	i3-msg workspace 1
	i3-msg fullscreen disable
	alacritty -o window.startup_mode=Fullscreen -e bash -c 'sleep 0.1 && cmatrix -ab -C cyan' &
	pid2=$!
	xtrlock
	kill $pid1
	kill $pid2
}
case "$1" in
    lock)
		if [ "$(playerctl status)" == "Playing" ]; then
			playerctl play-pause
			lock
			playerctl play-pause
		else
			lock
		fi
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|reboot|shutdown}"
        exit 2
esac

exit 0
