#!/bin/sh

if [ $# -lt 2 ]; then
	echo "usage: $0 <ssid> <key>"
	exit 99
fi

SSID="$1"
KEY="$2"
FILE=/tmp/wpa.conf
wpa_passphrase "$SSID" "$KEY" > $FILE
sudo killall -9 wpa_supplicant
sudo wpa_supplicant -B -i wlp4s0 -c $FILE &>/dev/null
sleep 5
sudo dhclient -r wlp4s0
sudo dhclient wlp4s0

rm -rf $FILE
