# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
separator_block_width=15

[volume]
label=Volume:
command=~/dotfiles/.i3/volume get
interval=once
signal=1

[memory]
label=(free RAM)
command=~/dotfiles/.i3/memory
interval=5

[disk-home]
label=
command=~/dotfiles/.i3/disk
interval=30

[wireless]
label=
instance=wlp4s0
command=~/dotfiles/.i3/iface
color=#00FF00
interval=10

[enp5s0]
label=(Uplink)
instance=enp5s0
command=~/dotfiles/.i3/iface
color=#00FF00
interval=10

[dg400]
label= (DG400)
instance=enp5s0.400
command=~/dotfiles/.i3/iface
color=#00FF00
interval=10

[dg301]
label= (DG301)
instance=enp5s0.401
command=~/dotfiles/.i3/iface
color=#00FF00
interval=10

[eg300]
label= (EG300)
instance=enp5s0.402
command=~/dotfiles/.i3/iface
color=#00FF00
interval=10

[dg301]
label= (DG301)
instance=enx00e04c680484
command=~/dotfiles/.i3/iface
color=#00FF00
interval=10

[NET]
label=
command=~/dotfiles/.i3/net_usage
interval=5
separator=false

[cpu]
label=
command=~/dotfiles/.i3/cpu_usage
interval=1
separator=false

[load]
label=avg
command=/usr/share/i3blocks/load_average
interval=10

[battery]
label=BAT
label=⚡
command=/usr/share/i3blocks/battery
interval=30

[time]
color=#d9b3ff
command=echo   $(date '+%b-%d %H:%M:%S')
interval=1
