# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
separator_block_width=15

[volume]
command=sleep .1;~/.i3/volume get
interval=repeat

[memory]
label=
command=~/.i3/memory
interval=5

#[swap]
#label=SWAP
#instance=swap
#command=/usr/share/i3blocks/memory
#interval=30

[disk-home]
label=
command=~/.i3/disk
interval=30

[wireless]
label=
instance=wlan0
#instance=wlp3s0
command=~/.i3/iface
color=#00FF00
interval=10

[ethernet0]
label=(eth0)
instance=eth0
command=~/.i3/iface
color=#00FF00
interval=10

[ethernet1]
label=(eth1)
instance=eth1
command=~/.i3/iface
color=#00FF00
interval=10

[ethernet2]
label=(eth2)
instance=eth2
command=~/.i3/iface
color=#00FF00
interval=10


[cpu]
label=
command=~/.i3/cpu_usage
interval=10
#separator=false

#[load]
#command=/usr/share/i3blocks/load_average
#interval=10

[battery]
label=BAT
#label=⚡
command=/usr/share/i3blocks/battery
interval=30

[time]
command=echo   $(date '+%b-%d %H:%M:%S')
interval=1
