#!/bin/sh
case "$1" in
    lock)
		DIR="/home/reidar/.wallpapers/png"
		PIC=$(ls $DIR/*.png | shuf -n 1)
		i3lock -i $PIC -t
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|reboot|shutdown}"
        exit 2
esac

exit 0
