#!/bin/sh
case "$1" in
    lock)
		DIR="/home/reidar/.wallpapers/"
		PIC=$(ls $DIR/*.png | shuf -n 1)
		i3lock -u -i $PIC -t
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
        ;;
    shutdown)
        dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
        ;;
    *)
        echo "Usage: $0 {lock|logout|reboot|shutdown}"
        exit 2
esac

exit 0
