#!/bin/bash

TYPE="mem"

awk '
	/^MemTotal:/ {
		mem_total=$2
	}
	/^MemFree:/ {
		mem_free=$2
	}
	/^Buffers:/ {
		mem_free+=$2
	}
	/^Cached:/ {
		mem_free+=$2
	}
	END {
		printf("%.1fG\n", mem_free/1024/1024)
		printf("%.1fG\n", mem_free/1024/1024)
		printf("#b35900\n")
	}
' /proc/meminfo
