#!/bin/bash

TYPE="mem"

awk '
	/^MemTotal:/ {
		mem_total=$2
	}
	/^MemFree:/ {
		used=$2
	}
	END {
		free = mem_total - used
		printf("%.2f%\n", used/mem_total)
		printf("%.2f%\n", used/mem_total)
		if(used/mem_total > 50)
			printf("#ff1000\n")
		else
			printf("#b35900\n")
	}
' /proc/meminfo
