#!/bin/bash
usage="$(ifstat -S 5 1 | grep -o '[0-9]*\.[0-9]*')"

down="$(echo $usage | cut -d ' ' -f2 | cut -d '.' -f 1)"
up="$(echo $usage | cut -d ' ' -f1 | cut -d '.' -f 1)"

if [ ${#down} -lt 4 ]; then
	echo -n " $down bit/s "
elif [ ${#down} -lt 7 ]; then
	echo -n " ${down:0:3}.${down:3} Mbit/s "
else
	echo -n " ${down:0:3}.${down:3:3} Gbit/s "
fi
if [ ${#up} -lt 4 ]; then
	echo -n " $up bit/s "
elif [ ${#up} -lt 7 ]; then
	echo -n " ${up:0:3}.${up:3} Mbit/s "
else
	echo -n " ${up:0:3}.${up:3:3} Gbit/s "
fi
