#!/bin/sh
case "$1" in
    lock)
		DIR="$HOME/.wallpapers"
		PIC=$(ls $DIR/*.png | shuf -n 1)
		if [ "$(playerctl status)" == "Playing" ]; then
			playerctl play-pause
			i3lock -n -i $PIC -t
			playerctl play-pause
		else
			i3lock -i $PIC -t
		fi
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|reboot|shutdown}"
        exit 2
esac

exit 0
