#!/bin/bash
usage="$(ifstat -S 5 1 | grep -o '[0-9]*\.[0-9]*')"

down="$(echo $usage | cut -d ' ' -f2 | cut -d '.' -f 1)"
up="$(echo $usage | cut -d ' ' -f1 | cut -d '.' -f 1)"

if [ ${#down} -lt 4 ]; then
	printf " %-4s b/s " $down
elif [ ${#down} -lt 7 ]; then
	printf " %-3s Mb/s " ${down::-3}
else
	printf " %-3s Gb/s " ${down::-3}
fi
if [ ${#up} -lt 4 ]; then
	printf " %-4s b/s\n" $up
elif [ ${#up} -lt 7 ]; then
	printf " %-3s Mb/s\n" ${up::-3}
else
	printf " %-3s Gb/s\n" ${up::-3}
fi

printf " %s b/s %d \n" $down ${#down}
if [ ${#down} -gt 3 ]; then
	printf "##FACC2E\n"
else
	printf "#ffffff\n"
fi
